#
# Generated by erpcgen 1.9.0 on Thu May 26 15:38:53 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for BBCarService
class IBBCarService(object):
    SERVICE_ID = 1
    INFO_ID = 1

    def info(self):
        raise NotImplementedError()


